#!/usr/bin/env python3
"""Copy named functions out of a decomp source file into a standalone C file for the parity library.

The copy keeps the source file's include block (quoted includes rewritten to the source directory),
the named functions and every static helper of that file they call, all verbatim, so the parity
harness exercises exactly the code the game DLL compiles. Regenerated by the build; not a source.

    python tools/fma_exact/extract_funcs.py <src.c> <out.c> <function> [<function> ...]
"""
import re
import sys
from pathlib import Path


def main():
    src, out, names = Path(sys.argv[1]).resolve(), Path(sys.argv[2]), sys.argv[3:]
    text = src.read_text(encoding='utf-8')
    includes = []
    for line in text.split('\n'):
        m = re.match(r'\s*#include\s+"([^"]+)"', line)
        if m:
            local = src.parent / m.group(1)
            includes.append('#include "%s"' % local.as_posix() if local.is_file() else line)
        elif re.match(r'\s*#include\s+<', line):
            includes.append(line)

    def definition(name):
        m = re.search(r'^(?:static\s+)?(?:inline\s+)?[A-Za-z_][\w\s\*]*?\b' + re.escape(name) + r'\s*\([^;{]*\)\s*\{',
                      text, flags=re.M)
        if not m:
            return None
        i, depth = m.end() - 1, 0
        while True:
            if text[i] == '{':
                depth += 1
            elif text[i] == '}':
                depth -= 1
                if depth == 0:
                    break
            i += 1
        return m.start(), text[m.start():i + 1]

    chosen, todo = {}, list(names)
    while todo:
        name = todo.pop()
        if name in chosen:
            continue
        d = definition(name)
        if d is None:
            if name in names:
                raise SystemExit('no definition of ' + name)
            continue
        chosen[name] = d
        for callee in set(re.findall(r'\b([A-Za-z_]\w*)\s*\(', d[1])):
            if callee not in chosen and re.search(r'^static\b[^;{]*\b' + re.escape(callee) + r'\s*\(', text, flags=re.M):
                todo.append(callee)
    body = [d[1] for d in sorted(chosen.values())]   # file order keeps helpers before their callers
    out.write_text('/* Generated by tools/fma_exact/extract_funcs.py from %s. Do not edit. */\n%s\n\n%s\n'
                   % (src.as_posix(), '\n'.join(includes), '\n\n'.join(body)), encoding='utf-8')
    print('%s: %d functions' % (out, len(body)))


if __name__ == '__main__':
    main()
