/* Generated by tools/tmce/gen_mextk.py: MexTK values that the decomp keeps as separate bitfields.
 * Console bit order within a byte is reversed natively, so these read and write each bit where the
 * native build keeps it. mexbits_get_<Type>__<path>(object), mexbits_set_<Type>__<path>(object, value). */
#pragma once
static inline unsigned int mexbits_get_FighterData__cpu_xf8(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[9072] >> 0) & 1) << 31;
    v |= (unsigned int)((b[9072] >> 2) & 1) << 30;
    v |= (unsigned int)((b[9072] >> 1) & 1) << 29;
    v |= (unsigned int)((b[9072] >> 4) & 1) << 28;
    v |= (unsigned int)((b[9072] >> 3) & 1) << 27;
    v |= (unsigned int)((b[9072] >> 5) & 1) << 26;
    v |= (unsigned int)((b[9072] >> 6) & 1) << 25;
    v |= (unsigned int)((b[9072] >> 7) & 1) << 24;
    v |= (unsigned int)((b[9073] >> 0) & 1) << 23;
    v |= (unsigned int)((b[9073] >> 1) & 1) << 22;
    v |= (unsigned int)((b[9073] >> 2) & 1) << 21;
    v |= (unsigned int)((b[9073] >> 3) & 1) << 20;
    v |= (unsigned int)((b[9073] >> 4) & 1) << 19;
    v |= (unsigned int)((b[9073] >> 5) & 1) << 18;
    v |= (unsigned int)((b[9073] >> 6) & 1) << 17;
    v |= (unsigned int)((b[9073] >> 7) & 1) << 16;
    v |= (unsigned int)((b[9074] >> 0) & 1) << 15;
    v |= (unsigned int)((b[9074] >> 1) & 1) << 14;
    v |= (unsigned int)((b[9074] >> 2) & 1) << 13;
    v |= (unsigned int)((b[9074] >> 4) & 1) << 12;
    v |= (unsigned int)((b[9074] >> 3) & 1) << 11;
    v |= (unsigned int)((b[9074] >> 5) & 1) << 10;
    v |= (unsigned int)((b[9074] >> 6) & 1) << 9;
    v |= (unsigned int)((b[9074] >> 7) & 1) << 8;
    v |= (unsigned int)((b[9075] >> 0) & 1) << 7;
    v |= (unsigned int)((b[9075] >> 1) & 1) << 6;
    v |= (unsigned int)((b[9075] >> 2) & 1) << 5;
    v |= (unsigned int)((b[9075] >> 3) & 1) << 4;
    v |= (unsigned int)((b[9075] >> 4) & 1) << 3;
    v |= (unsigned int)((b[9075] >> 5) & 1) << 2;
    v |= (unsigned int)((b[9075] >> 6) & 1) << 1;
    v |= (unsigned int)((b[9075] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_FighterData__cpu_xf8(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[9072] = (unsigned char)((b[9072] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[9072] = (unsigned char)((b[9072] & ~(1u << 2)) | (((v >> 30) & 1u) << 2));
    b[9072] = (unsigned char)((b[9072] & ~(1u << 1)) | (((v >> 29) & 1u) << 1));
    b[9072] = (unsigned char)((b[9072] & ~(1u << 4)) | (((v >> 28) & 1u) << 4));
    b[9072] = (unsigned char)((b[9072] & ~(1u << 3)) | (((v >> 27) & 1u) << 3));
    b[9072] = (unsigned char)((b[9072] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[9072] = (unsigned char)((b[9072] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[9072] = (unsigned char)((b[9072] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[9073] = (unsigned char)((b[9073] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 0)) | (((v >> 15) & 1u) << 0));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 1)) | (((v >> 14) & 1u) << 1));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 2)) | (((v >> 13) & 1u) << 2));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 5)) | (((v >> 10) & 1u) << 5));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 6)) | (((v >> 9) & 1u) << 6));
    b[9074] = (unsigned char)((b[9074] & ~(1u << 7)) | (((v >> 8) & 1u) << 7));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 0)) | (((v >> 7) & 1u) << 0));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 1)) | (((v >> 6) & 1u) << 1));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 2)) | (((v >> 5) & 1u) << 2));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[9075] = (unsigned char)((b[9075] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_FighterData__flags_can_input_multijump(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[10940] >> 2) & 1) << 7;
    v |= (unsigned int)((b[10940] >> 1) & 1) << 6;
    v |= (unsigned int)((b[10940] >> 0) & 1) << 5;
    v |= (unsigned int)((b[10940] >> 3) & 1) << 4;
    v |= (unsigned int)((b[10940] >> 4) & 1) << 3;
    v |= (unsigned int)((b[10940] >> 5) & 1) << 2;
    v |= (unsigned int)((b[10940] >> 6) & 1) << 1;
    v |= (unsigned int)((b[10940] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_FighterData__flags_can_input_multijump(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[10940] = (unsigned char)((b[10940] & ~(1u << 2)) | (((v >> 7) & 1u) << 2));
    b[10940] = (unsigned char)((b[10940] & ~(1u << 1)) | (((v >> 6) & 1u) << 1));
    b[10940] = (unsigned char)((b[10940] & ~(1u << 0)) | (((v >> 5) & 1u) << 0));
    b[10940] = (unsigned char)((b[10940] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[10940] = (unsigned char)((b[10940] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[10940] = (unsigned char)((b[10940] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[10940] = (unsigned char)((b[10940] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[10940] = (unsigned char)((b[10940] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_FighterData__flags_flags_2221(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[10941] >> 0) & 1) << 7;
    v |= (unsigned int)((b[10941] >> 1) & 1) << 6;
    v |= (unsigned int)((b[10941] >> 2) & 1) << 5;
    v |= (unsigned int)((b[10941] >> 3) & 1) << 4;
    v |= (unsigned int)((b[10941] >> 4) & 1) << 3;
    v |= (unsigned int)((b[10941] >> 5) & 1) << 2;
    v |= (unsigned int)((b[10941] >> 6) & 1) << 1;
    v |= (unsigned int)((b[10941] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_FighterData__flags_flags_2221(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[10941] = (unsigned char)((b[10941] & ~(1u << 0)) | (((v >> 7) & 1u) << 0));
    b[10941] = (unsigned char)((b[10941] & ~(1u << 1)) | (((v >> 6) & 1u) << 1));
    b[10941] = (unsigned char)((b[10941] & ~(1u << 2)) | (((v >> 5) & 1u) << 2));
    b[10941] = (unsigned char)((b[10941] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[10941] = (unsigned char)((b[10941] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[10941] = (unsigned char)((b[10941] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[10941] = (unsigned char)((b[10941] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[10941] = (unsigned char)((b[10941] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_FighterData__flags_flags_2227(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[10947] >> 0) & 1) << 7;
    v |= (unsigned int)((b[10947] >> 1) & 1) << 6;
    v |= (unsigned int)((b[10947] >> 2) & 1) << 5;
    v |= (unsigned int)((b[10947] >> 3) & 1) << 4;
    v |= (unsigned int)((b[10947] >> 4) & 1) << 3;
    v |= (unsigned int)((b[10947] >> 5) & 1) << 2;
    v |= (unsigned int)((b[10947] >> 6) & 1) << 1;
    v |= (unsigned int)((b[10947] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_FighterData__flags_flags_2227(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[10947] = (unsigned char)((b[10947] & ~(1u << 0)) | (((v >> 7) & 1u) << 0));
    b[10947] = (unsigned char)((b[10947] & ~(1u << 1)) | (((v >> 6) & 1u) << 1));
    b[10947] = (unsigned char)((b[10947] & ~(1u << 2)) | (((v >> 5) & 1u) << 2));
    b[10947] = (unsigned char)((b[10947] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[10947] = (unsigned char)((b[10947] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[10947] = (unsigned char)((b[10947] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[10947] = (unsigned char)((b[10947] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[10947] = (unsigned char)((b[10947] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_ItemData__xdc8(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[4900] >> 0) & 1) << 7;
    v |= (unsigned int)((b[4900] >> 1) & 1) << 6;
    v |= (unsigned int)((b[4900] >> 2) & 1) << 5;
    v |= (unsigned int)((b[4900] >> 3) & 1) << 4;
    v |= (unsigned int)((b[4900] >> 4) & 1) << 3;
    v |= (unsigned int)((b[4900] >> 5) & 1) << 2;
    v |= (unsigned int)((b[4900] >> 6) & 1) << 1;
    v |= (unsigned int)((b[4900] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_ItemData__xdc8(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[4900] = (unsigned char)((b[4900] & ~(1u << 0)) | (((v >> 7) & 1u) << 0));
    b[4900] = (unsigned char)((b[4900] & ~(1u << 1)) | (((v >> 6) & 1u) << 1));
    b[4900] = (unsigned char)((b[4900] & ~(1u << 2)) | (((v >> 5) & 1u) << 2));
    b[4900] = (unsigned char)((b[4900] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[4900] = (unsigned char)((b[4900] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[4900] = (unsigned char)((b[4900] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[4900] = (unsigned char)((b[4900] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[4900] = (unsigned char)((b[4900] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_ItemData__xdc9_f(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[4901] >> 4) & 1) << 3;
    v |= (unsigned int)((b[4901] >> 5) & 1) << 2;
    v |= (unsigned int)((b[4901] >> 6) & 1) << 1;
    v |= (unsigned int)((b[4902] >> 2) & 1) << 0;
    return v;
}
static inline void mexbits_set_ItemData__xdc9_f(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[4901] = (unsigned char)((b[4901] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[4901] = (unsigned char)((b[4901] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[4901] = (unsigned char)((b[4901] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[4902] = (unsigned char)((b[4902] & ~(1u << 2)) | (((v >> 0) & 1u) << 2));
}
static inline unsigned int mexbits_get_ItemData__xdcb_5(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[4903] >> 5) & 1) << 1;
    v |= (unsigned int)((b[4903] >> 6) & 1) << 0;
    return v;
}
static inline void mexbits_set_ItemData__xdcb_5(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[4903] = (unsigned char)((b[4903] & ~(1u << 5)) | (((v >> 1) & 1u) << 5));
    b[4903] = (unsigned char)((b[4903] & ~(1u << 6)) | (((v >> 0) & 1u) << 6));
}
static inline unsigned int mexbits_get_DevText__x27(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[39] >> 5) & 1) << 7;
    v |= (unsigned int)((b[39] >> 4) & 1) << 6;
    v |= (unsigned int)((b[39] >> 3) & 1) << 5;
    v |= (unsigned int)((b[39] >> 2) & 1) << 4;
    v |= (unsigned int)((b[39] >> 1) & 1) << 3;
    v |= (unsigned int)((b[39] >> 0) & 1) << 2;
    v |= (unsigned int)((b[39] >> 7) & 1) << 1;
    v |= (unsigned int)((b[39] >> 6) & 1) << 0;
    return v;
}
static inline void mexbits_set_DevText__x27(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[39] = (unsigned char)((b[39] & ~(1u << 5)) | (((v >> 7) & 1u) << 5));
    b[39] = (unsigned char)((b[39] & ~(1u << 4)) | (((v >> 6) & 1u) << 4));
    b[39] = (unsigned char)((b[39] & ~(1u << 3)) | (((v >> 5) & 1u) << 3));
    b[39] = (unsigned char)((b[39] & ~(1u << 2)) | (((v >> 4) & 1u) << 2));
    b[39] = (unsigned char)((b[39] & ~(1u << 1)) | (((v >> 3) & 1u) << 1));
    b[39] = (unsigned char)((b[39] & ~(1u << 0)) | (((v >> 2) & 1u) << 0));
    b[39] = (unsigned char)((b[39] & ~(1u << 7)) | (((v >> 1) & 1u) << 7));
    b[39] = (unsigned char)((b[39] & ~(1u << 6)) | (((v >> 0) & 1u) << 6));
}
static inline unsigned int mexbits_get_MatchInit__timer(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[0] >> 6) & 1) << 1;
    v |= (unsigned int)((b[0] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_MatchInit__timer(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[0] = (unsigned char)((b[0] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[0] = (unsigned char)((b[0] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_MatchInit__unk1f(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[4] >> 5) & 1) << 2;
    v |= (unsigned int)((b[4] >> 6) & 1) << 1;
    v |= (unsigned int)((b[4] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_MatchInit__unk1f(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[4] = (unsigned char)((b[4] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[4] = (unsigned char)((b[4] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[4] = (unsigned char)((b[4] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_MatchInit__unk12(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[5] >> 3) & 1) << 4;
    v |= (unsigned int)((b[5] >> 4) & 1) << 3;
    v |= (unsigned int)((b[5] >> 5) & 1) << 2;
    v |= (unsigned int)((b[5] >> 6) & 1) << 1;
    v |= (unsigned int)((b[5] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_MatchInit__unk12(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[5] = (unsigned char)((b[5] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[5] = (unsigned char)((b[5] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[5] = (unsigned char)((b[5] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[5] = (unsigned char)((b[5] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[5] = (unsigned char)((b[5] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_ftHit__x40(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[64] >> 0) & 1) << 7;
    v |= (unsigned int)((b[64] >> 1) & 1) << 6;
    v |= (unsigned int)((b[64] >> 2) & 1) << 5;
    v |= (unsigned int)((b[64] >> 3) & 1) << 4;
    v |= (unsigned int)((b[65] >> 3) & 1) << 3;
    v |= (unsigned int)((b[65] >> 2) & 1) << 2;
    v |= (unsigned int)((b[65] >> 1) & 1) << 1;
    v |= (unsigned int)((b[65] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_ftHit__x40(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[64] = (unsigned char)((b[64] & ~(1u << 0)) | (((v >> 7) & 1u) << 0));
    b[64] = (unsigned char)((b[64] & ~(1u << 1)) | (((v >> 6) & 1u) << 1));
    b[64] = (unsigned char)((b[64] & ~(1u << 2)) | (((v >> 5) & 1u) << 2));
    b[64] = (unsigned char)((b[64] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[65] = (unsigned char)((b[65] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[65] = (unsigned char)((b[65] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[65] = (unsigned char)((b[65] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[65] = (unsigned char)((b[65] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_ftHit__x41(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[64] >> 7) & 1) << 7;
    v |= (unsigned int)((b[64] >> 6) & 1) << 6;
    v |= (unsigned int)((b[64] >> 5) & 1) << 5;
    v |= (unsigned int)((b[64] >> 4) & 1) << 4;
    v |= (unsigned int)((b[65] >> 4) & 1) << 3;
    v |= (unsigned int)((b[65] >> 5) & 1) << 2;
    v |= (unsigned int)((b[65] >> 6) & 1) << 1;
    v |= (unsigned int)((b[65] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_ftHit__x41(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[64] = (unsigned char)((b[64] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[64] = (unsigned char)((b[64] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[64] = (unsigned char)((b[64] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[64] = (unsigned char)((b[64] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[65] = (unsigned char)((b[65] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[65] = (unsigned char)((b[65] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[65] = (unsigned char)((b[65] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[65] = (unsigned char)((b[65] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_itHit__x138(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[512] >> 0) & 1) << 31;
    v |= (unsigned int)((b[512] >> 7) & 1) << 30;
    v |= (unsigned int)((b[512] >> 6) & 1) << 29;
    v |= (unsigned int)((b[512] >> 5) & 1) << 28;
    v |= (unsigned int)((b[512] >> 4) & 1) << 27;
    v |= (unsigned int)((b[512] >> 3) & 1) << 26;
    v |= (unsigned int)((b[512] >> 2) & 1) << 25;
    v |= (unsigned int)((b[512] >> 1) & 1) << 24;
    v |= (unsigned int)((b[513] >> 7) & 1) << 23;
    v |= (unsigned int)((b[513] >> 6) & 1) << 22;
    v |= (unsigned int)((b[513] >> 5) & 1) << 21;
    v |= (unsigned int)((b[513] >> 4) & 1) << 20;
    v |= (unsigned int)((b[513] >> 3) & 1) << 19;
    v |= (unsigned int)((b[513] >> 2) & 1) << 18;
    v |= (unsigned int)((b[513] >> 1) & 1) << 17;
    v |= (unsigned int)((b[513] >> 0) & 1) << 16;
    v |= (unsigned int)((b[514] >> 7) & 1) << 15;
    v |= (unsigned int)((b[514] >> 6) & 1) << 14;
    v |= (unsigned int)((b[514] >> 5) & 1) << 13;
    v |= (unsigned int)((b[514] >> 4) & 1) << 12;
    v |= (unsigned int)((b[514] >> 3) & 1) << 11;
    v |= (unsigned int)((b[514] >> 2) & 1) << 10;
    v |= (unsigned int)((b[514] >> 1) & 1) << 9;
    v |= (unsigned int)((b[514] >> 0) & 1) << 8;
    v |= (unsigned int)((b[515] >> 7) & 1) << 7;
    v |= (unsigned int)((b[515] >> 6) & 1) << 6;
    v |= (unsigned int)((b[515] >> 5) & 1) << 5;
    v |= (unsigned int)((b[515] >> 4) & 1) << 4;
    v |= (unsigned int)((b[515] >> 3) & 1) << 3;
    v |= (unsigned int)((b[515] >> 2) & 1) << 2;
    v |= (unsigned int)((b[515] >> 1) & 1) << 1;
    v |= (unsigned int)((b[515] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_itHit__x138(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[512] = (unsigned char)((b[512] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[512] = (unsigned char)((b[512] & ~(1u << 7)) | (((v >> 30) & 1u) << 7));
    b[512] = (unsigned char)((b[512] & ~(1u << 6)) | (((v >> 29) & 1u) << 6));
    b[512] = (unsigned char)((b[512] & ~(1u << 5)) | (((v >> 28) & 1u) << 5));
    b[512] = (unsigned char)((b[512] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[512] = (unsigned char)((b[512] & ~(1u << 3)) | (((v >> 26) & 1u) << 3));
    b[512] = (unsigned char)((b[512] & ~(1u << 2)) | (((v >> 25) & 1u) << 2));
    b[512] = (unsigned char)((b[512] & ~(1u << 1)) | (((v >> 24) & 1u) << 1));
    b[513] = (unsigned char)((b[513] & ~(1u << 7)) | (((v >> 23) & 1u) << 7));
    b[513] = (unsigned char)((b[513] & ~(1u << 6)) | (((v >> 22) & 1u) << 6));
    b[513] = (unsigned char)((b[513] & ~(1u << 5)) | (((v >> 21) & 1u) << 5));
    b[513] = (unsigned char)((b[513] & ~(1u << 4)) | (((v >> 20) & 1u) << 4));
    b[513] = (unsigned char)((b[513] & ~(1u << 3)) | (((v >> 19) & 1u) << 3));
    b[513] = (unsigned char)((b[513] & ~(1u << 2)) | (((v >> 18) & 1u) << 2));
    b[513] = (unsigned char)((b[513] & ~(1u << 1)) | (((v >> 17) & 1u) << 1));
    b[513] = (unsigned char)((b[513] & ~(1u << 0)) | (((v >> 16) & 1u) << 0));
    b[514] = (unsigned char)((b[514] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[514] = (unsigned char)((b[514] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[514] = (unsigned char)((b[514] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[514] = (unsigned char)((b[514] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[514] = (unsigned char)((b[514] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[514] = (unsigned char)((b[514] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[514] = (unsigned char)((b[514] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[514] = (unsigned char)((b[514] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[515] = (unsigned char)((b[515] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[515] = (unsigned char)((b[515] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[515] = (unsigned char)((b[515] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[515] = (unsigned char)((b[515] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[515] = (unsigned char)((b[515] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[515] = (unsigned char)((b[515] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[515] = (unsigned char)((b[515] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[515] = (unsigned char)((b[515] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Match__match_timer(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[9432] >> 6) & 1) << 1;
    v |= (unsigned int)((b[9432] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_Match__match_timer(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[9432] = (unsigned char)((b[9432] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[9432] = (unsigned char)((b[9432] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_Match__match_unk1f(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[9436] >> 5) & 1) << 2;
    v |= (unsigned int)((b[9436] >> 6) & 1) << 1;
    v |= (unsigned int)((b[9436] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_Match__match_unk1f(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[9436] = (unsigned char)((b[9436] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[9436] = (unsigned char)((b[9436] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[9436] = (unsigned char)((b[9436] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_Match__match_unk12(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[9437] >> 3) & 1) << 4;
    v |= (unsigned int)((b[9437] >> 4) & 1) << 3;
    v |= (unsigned int)((b[9437] >> 5) & 1) << 2;
    v |= (unsigned int)((b[9437] >> 6) & 1) << 1;
    v |= (unsigned int)((b[9437] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_Match__match_unk12(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[9437] = (unsigned char)((b[9437] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[9437] = (unsigned char)((b[9437] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[9437] = (unsigned char)((b[9437] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[9437] = (unsigned char)((b[9437] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[9437] = (unsigned char)((b[9437] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_PlayerData__unk2(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[12] >> 2) & 1) << 5;
    v |= (unsigned int)((b[12] >> 3) & 1) << 4;
    v |= (unsigned int)((b[12] >> 4) & 1) << 3;
    v |= (unsigned int)((b[12] >> 5) & 1) << 2;
    v |= (unsigned int)((b[12] >> 6) & 1) << 1;
    v |= (unsigned int)((b[12] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_PlayerData__unk2(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[12] = (unsigned char)((b[12] & ~(1u << 2)) | (((v >> 5) & 1u) << 2));
    b[12] = (unsigned char)((b[12] & ~(1u << 3)) | (((v >> 4) & 1u) << 3));
    b[12] = (unsigned char)((b[12] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[12] = (unsigned char)((b[12] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[12] = (unsigned char)((b[12] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[12] = (unsigned char)((b[12] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_PlayerData__xd_3f(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[13] >> 4) & 1) << 3;
    v |= (unsigned int)((b[13] >> 5) & 1) << 2;
    v |= (unsigned int)((b[13] >> 6) & 1) << 1;
    v |= (unsigned int)((b[13] >> 7) & 1) << 0;
    return v;
}
static inline void mexbits_set_PlayerData__xd_3f(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[13] = (unsigned char)((b[13] & ~(1u << 4)) | (((v >> 3) & 1u) << 4));
    b[13] = (unsigned char)((b[13] & ~(1u << 5)) | (((v >> 2) & 1u) << 5));
    b[13] = (unsigned char)((b[13] & ~(1u << 6)) | (((v >> 1) & 1u) << 6));
    b[13] = (unsigned char)((b[13] & ~(1u << 7)) | (((v >> 0) & 1u) << 7));
}
static inline unsigned int mexbits_get_Memcard__unk14(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[56] >> 7) & 1) << 31;
    v |= (unsigned int)((b[56] >> 6) & 1) << 30;
    v |= (unsigned int)((b[56] >> 5) & 1) << 29;
    v |= (unsigned int)((b[56] >> 4) & 1) << 28;
    v |= (unsigned int)((b[56] >> 3) & 1) << 27;
    v |= (unsigned int)((b[56] >> 2) & 1) << 26;
    v |= (unsigned int)((b[56] >> 1) & 1) << 25;
    v |= (unsigned int)((b[56] >> 0) & 1) << 24;
    v |= (unsigned int)((b[57] >> 7) & 1) << 23;
    v |= (unsigned int)((b[57] >> 6) & 1) << 22;
    v |= (unsigned int)((b[57] >> 5) & 1) << 21;
    v |= (unsigned int)((b[57] >> 4) & 1) << 20;
    v |= (unsigned int)((b[57] >> 3) & 1) << 19;
    v |= (unsigned int)((b[57] >> 2) & 1) << 18;
    v |= (unsigned int)((b[57] >> 1) & 1) << 17;
    v |= (unsigned int)((b[57] >> 0) & 1) << 16;
    v |= (unsigned int)((b[58] >> 7) & 1) << 15;
    v |= (unsigned int)((b[58] >> 6) & 1) << 14;
    v |= (unsigned int)((b[58] >> 5) & 1) << 13;
    v |= (unsigned int)((b[58] >> 4) & 1) << 12;
    v |= (unsigned int)((b[58] >> 3) & 1) << 11;
    v |= (unsigned int)((b[58] >> 2) & 1) << 10;
    v |= (unsigned int)((b[58] >> 1) & 1) << 9;
    v |= (unsigned int)((b[58] >> 0) & 1) << 8;
    v |= (unsigned int)((b[59] >> 7) & 1) << 7;
    v |= (unsigned int)((b[59] >> 6) & 1) << 6;
    v |= (unsigned int)((b[59] >> 5) & 1) << 5;
    v |= (unsigned int)((b[59] >> 4) & 1) << 4;
    v |= (unsigned int)((b[59] >> 3) & 1) << 3;
    v |= (unsigned int)((b[59] >> 2) & 1) << 2;
    v |= (unsigned int)((b[59] >> 1) & 1) << 1;
    v |= (unsigned int)((b[59] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk14(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[56] = (unsigned char)((b[56] & ~(1u << 7)) | (((v >> 31) & 1u) << 7));
    b[56] = (unsigned char)((b[56] & ~(1u << 6)) | (((v >> 30) & 1u) << 6));
    b[56] = (unsigned char)((b[56] & ~(1u << 5)) | (((v >> 29) & 1u) << 5));
    b[56] = (unsigned char)((b[56] & ~(1u << 4)) | (((v >> 28) & 1u) << 4));
    b[56] = (unsigned char)((b[56] & ~(1u << 3)) | (((v >> 27) & 1u) << 3));
    b[56] = (unsigned char)((b[56] & ~(1u << 2)) | (((v >> 26) & 1u) << 2));
    b[56] = (unsigned char)((b[56] & ~(1u << 1)) | (((v >> 25) & 1u) << 1));
    b[56] = (unsigned char)((b[56] & ~(1u << 0)) | (((v >> 24) & 1u) << 0));
    b[57] = (unsigned char)((b[57] & ~(1u << 7)) | (((v >> 23) & 1u) << 7));
    b[57] = (unsigned char)((b[57] & ~(1u << 6)) | (((v >> 22) & 1u) << 6));
    b[57] = (unsigned char)((b[57] & ~(1u << 5)) | (((v >> 21) & 1u) << 5));
    b[57] = (unsigned char)((b[57] & ~(1u << 4)) | (((v >> 20) & 1u) << 4));
    b[57] = (unsigned char)((b[57] & ~(1u << 3)) | (((v >> 19) & 1u) << 3));
    b[57] = (unsigned char)((b[57] & ~(1u << 2)) | (((v >> 18) & 1u) << 2));
    b[57] = (unsigned char)((b[57] & ~(1u << 1)) | (((v >> 17) & 1u) << 1));
    b[57] = (unsigned char)((b[57] & ~(1u << 0)) | (((v >> 16) & 1u) << 0));
    b[58] = (unsigned char)((b[58] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[58] = (unsigned char)((b[58] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[58] = (unsigned char)((b[58] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[58] = (unsigned char)((b[58] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[58] = (unsigned char)((b[58] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[58] = (unsigned char)((b[58] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[58] = (unsigned char)((b[58] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[58] = (unsigned char)((b[58] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[59] = (unsigned char)((b[59] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[59] = (unsigned char)((b[59] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[59] = (unsigned char)((b[59] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[59] = (unsigned char)((b[59] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[59] = (unsigned char)((b[59] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[59] = (unsigned char)((b[59] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[59] = (unsigned char)((b[59] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[59] = (unsigned char)((b[59] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk359(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[1436] >> 0) & 1) << 31;
    v |= (unsigned int)((b[1436] >> 1) & 1) << 30;
    v |= (unsigned int)((b[1436] >> 2) & 1) << 29;
    v |= (unsigned int)((b[1436] >> 3) & 1) << 28;
    v |= (unsigned int)((b[1436] >> 4) & 1) << 27;
    v |= (unsigned int)((b[1436] >> 5) & 1) << 26;
    v |= (unsigned int)((b[1436] >> 6) & 1) << 25;
    v |= (unsigned int)((b[1436] >> 7) & 1) << 24;
    v |= (unsigned int)((b[1437] >> 0) & 1) << 23;
    v |= (unsigned int)((b[1437] >> 1) & 1) << 22;
    v |= (unsigned int)((b[1437] >> 2) & 1) << 21;
    v |= (unsigned int)((b[1437] >> 3) & 1) << 20;
    v |= (unsigned int)((b[1437] >> 4) & 1) << 19;
    v |= (unsigned int)((b[1437] >> 5) & 1) << 18;
    v |= (unsigned int)((b[1437] >> 6) & 1) << 17;
    v |= (unsigned int)((b[1437] >> 7) & 1) << 16;
    v |= (unsigned int)((b[1438] >> 7) & 1) << 15;
    v |= (unsigned int)((b[1438] >> 6) & 1) << 14;
    v |= (unsigned int)((b[1438] >> 5) & 1) << 13;
    v |= (unsigned int)((b[1438] >> 4) & 1) << 12;
    v |= (unsigned int)((b[1438] >> 3) & 1) << 11;
    v |= (unsigned int)((b[1438] >> 2) & 1) << 10;
    v |= (unsigned int)((b[1438] >> 1) & 1) << 9;
    v |= (unsigned int)((b[1438] >> 0) & 1) << 8;
    v |= (unsigned int)((b[1439] >> 7) & 1) << 7;
    v |= (unsigned int)((b[1439] >> 6) & 1) << 6;
    v |= (unsigned int)((b[1439] >> 5) & 1) << 5;
    v |= (unsigned int)((b[1439] >> 4) & 1) << 4;
    v |= (unsigned int)((b[1439] >> 3) & 1) << 3;
    v |= (unsigned int)((b[1439] >> 2) & 1) << 2;
    v |= (unsigned int)((b[1439] >> 1) & 1) << 1;
    v |= (unsigned int)((b[1439] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk359(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[1436] = (unsigned char)((b[1436] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[1436] = (unsigned char)((b[1436] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[1436] = (unsigned char)((b[1436] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[1436] = (unsigned char)((b[1436] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[1436] = (unsigned char)((b[1436] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[1436] = (unsigned char)((b[1436] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[1436] = (unsigned char)((b[1436] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[1436] = (unsigned char)((b[1436] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[1437] = (unsigned char)((b[1437] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[1438] = (unsigned char)((b[1438] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[1439] = (unsigned char)((b[1439] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk439(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[1796] >> 0) & 1) << 31;
    v |= (unsigned int)((b[1796] >> 1) & 1) << 30;
    v |= (unsigned int)((b[1796] >> 2) & 1) << 29;
    v |= (unsigned int)((b[1796] >> 3) & 1) << 28;
    v |= (unsigned int)((b[1796] >> 4) & 1) << 27;
    v |= (unsigned int)((b[1796] >> 5) & 1) << 26;
    v |= (unsigned int)((b[1796] >> 6) & 1) << 25;
    v |= (unsigned int)((b[1796] >> 7) & 1) << 24;
    v |= (unsigned int)((b[1797] >> 0) & 1) << 23;
    v |= (unsigned int)((b[1797] >> 1) & 1) << 22;
    v |= (unsigned int)((b[1797] >> 2) & 1) << 21;
    v |= (unsigned int)((b[1797] >> 3) & 1) << 20;
    v |= (unsigned int)((b[1797] >> 4) & 1) << 19;
    v |= (unsigned int)((b[1797] >> 5) & 1) << 18;
    v |= (unsigned int)((b[1797] >> 6) & 1) << 17;
    v |= (unsigned int)((b[1797] >> 7) & 1) << 16;
    v |= (unsigned int)((b[1798] >> 7) & 1) << 15;
    v |= (unsigned int)((b[1798] >> 6) & 1) << 14;
    v |= (unsigned int)((b[1798] >> 5) & 1) << 13;
    v |= (unsigned int)((b[1798] >> 4) & 1) << 12;
    v |= (unsigned int)((b[1798] >> 3) & 1) << 11;
    v |= (unsigned int)((b[1798] >> 2) & 1) << 10;
    v |= (unsigned int)((b[1798] >> 1) & 1) << 9;
    v |= (unsigned int)((b[1798] >> 0) & 1) << 8;
    v |= (unsigned int)((b[1799] >> 7) & 1) << 7;
    v |= (unsigned int)((b[1799] >> 6) & 1) << 6;
    v |= (unsigned int)((b[1799] >> 5) & 1) << 5;
    v |= (unsigned int)((b[1799] >> 4) & 1) << 4;
    v |= (unsigned int)((b[1799] >> 3) & 1) << 3;
    v |= (unsigned int)((b[1799] >> 2) & 1) << 2;
    v |= (unsigned int)((b[1799] >> 1) & 1) << 1;
    v |= (unsigned int)((b[1799] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk439(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[1796] = (unsigned char)((b[1796] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[1796] = (unsigned char)((b[1796] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[1796] = (unsigned char)((b[1796] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[1796] = (unsigned char)((b[1796] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[1796] = (unsigned char)((b[1796] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[1796] = (unsigned char)((b[1796] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[1796] = (unsigned char)((b[1796] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[1796] = (unsigned char)((b[1796] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[1797] = (unsigned char)((b[1797] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[1798] = (unsigned char)((b[1798] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[1799] = (unsigned char)((b[1799] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk519(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[2156] >> 0) & 1) << 31;
    v |= (unsigned int)((b[2156] >> 1) & 1) << 30;
    v |= (unsigned int)((b[2156] >> 2) & 1) << 29;
    v |= (unsigned int)((b[2156] >> 3) & 1) << 28;
    v |= (unsigned int)((b[2156] >> 4) & 1) << 27;
    v |= (unsigned int)((b[2156] >> 5) & 1) << 26;
    v |= (unsigned int)((b[2156] >> 6) & 1) << 25;
    v |= (unsigned int)((b[2156] >> 7) & 1) << 24;
    v |= (unsigned int)((b[2157] >> 0) & 1) << 23;
    v |= (unsigned int)((b[2157] >> 1) & 1) << 22;
    v |= (unsigned int)((b[2157] >> 2) & 1) << 21;
    v |= (unsigned int)((b[2157] >> 3) & 1) << 20;
    v |= (unsigned int)((b[2157] >> 4) & 1) << 19;
    v |= (unsigned int)((b[2157] >> 5) & 1) << 18;
    v |= (unsigned int)((b[2157] >> 6) & 1) << 17;
    v |= (unsigned int)((b[2157] >> 7) & 1) << 16;
    v |= (unsigned int)((b[2158] >> 7) & 1) << 15;
    v |= (unsigned int)((b[2158] >> 6) & 1) << 14;
    v |= (unsigned int)((b[2158] >> 5) & 1) << 13;
    v |= (unsigned int)((b[2158] >> 4) & 1) << 12;
    v |= (unsigned int)((b[2158] >> 3) & 1) << 11;
    v |= (unsigned int)((b[2158] >> 2) & 1) << 10;
    v |= (unsigned int)((b[2158] >> 1) & 1) << 9;
    v |= (unsigned int)((b[2158] >> 0) & 1) << 8;
    v |= (unsigned int)((b[2159] >> 7) & 1) << 7;
    v |= (unsigned int)((b[2159] >> 6) & 1) << 6;
    v |= (unsigned int)((b[2159] >> 5) & 1) << 5;
    v |= (unsigned int)((b[2159] >> 4) & 1) << 4;
    v |= (unsigned int)((b[2159] >> 3) & 1) << 3;
    v |= (unsigned int)((b[2159] >> 2) & 1) << 2;
    v |= (unsigned int)((b[2159] >> 1) & 1) << 1;
    v |= (unsigned int)((b[2159] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk519(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[2156] = (unsigned char)((b[2156] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[2156] = (unsigned char)((b[2156] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[2156] = (unsigned char)((b[2156] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[2156] = (unsigned char)((b[2156] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[2156] = (unsigned char)((b[2156] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[2156] = (unsigned char)((b[2156] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[2156] = (unsigned char)((b[2156] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[2156] = (unsigned char)((b[2156] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[2157] = (unsigned char)((b[2157] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[2158] = (unsigned char)((b[2158] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[2159] = (unsigned char)((b[2159] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk599(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[2516] >> 0) & 1) << 31;
    v |= (unsigned int)((b[2516] >> 1) & 1) << 30;
    v |= (unsigned int)((b[2516] >> 2) & 1) << 29;
    v |= (unsigned int)((b[2516] >> 3) & 1) << 28;
    v |= (unsigned int)((b[2516] >> 4) & 1) << 27;
    v |= (unsigned int)((b[2516] >> 5) & 1) << 26;
    v |= (unsigned int)((b[2516] >> 6) & 1) << 25;
    v |= (unsigned int)((b[2516] >> 7) & 1) << 24;
    v |= (unsigned int)((b[2517] >> 0) & 1) << 23;
    v |= (unsigned int)((b[2517] >> 1) & 1) << 22;
    v |= (unsigned int)((b[2517] >> 2) & 1) << 21;
    v |= (unsigned int)((b[2517] >> 3) & 1) << 20;
    v |= (unsigned int)((b[2517] >> 4) & 1) << 19;
    v |= (unsigned int)((b[2517] >> 5) & 1) << 18;
    v |= (unsigned int)((b[2517] >> 6) & 1) << 17;
    v |= (unsigned int)((b[2517] >> 7) & 1) << 16;
    v |= (unsigned int)((b[2518] >> 7) & 1) << 15;
    v |= (unsigned int)((b[2518] >> 6) & 1) << 14;
    v |= (unsigned int)((b[2518] >> 5) & 1) << 13;
    v |= (unsigned int)((b[2518] >> 4) & 1) << 12;
    v |= (unsigned int)((b[2518] >> 3) & 1) << 11;
    v |= (unsigned int)((b[2518] >> 2) & 1) << 10;
    v |= (unsigned int)((b[2518] >> 1) & 1) << 9;
    v |= (unsigned int)((b[2518] >> 0) & 1) << 8;
    v |= (unsigned int)((b[2519] >> 7) & 1) << 7;
    v |= (unsigned int)((b[2519] >> 6) & 1) << 6;
    v |= (unsigned int)((b[2519] >> 5) & 1) << 5;
    v |= (unsigned int)((b[2519] >> 4) & 1) << 4;
    v |= (unsigned int)((b[2519] >> 3) & 1) << 3;
    v |= (unsigned int)((b[2519] >> 2) & 1) << 2;
    v |= (unsigned int)((b[2519] >> 1) & 1) << 1;
    v |= (unsigned int)((b[2519] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk599(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[2516] = (unsigned char)((b[2516] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[2516] = (unsigned char)((b[2516] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[2516] = (unsigned char)((b[2516] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[2516] = (unsigned char)((b[2516] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[2516] = (unsigned char)((b[2516] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[2516] = (unsigned char)((b[2516] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[2516] = (unsigned char)((b[2516] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[2516] = (unsigned char)((b[2516] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[2517] = (unsigned char)((b[2517] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[2518] = (unsigned char)((b[2518] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[2519] = (unsigned char)((b[2519] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk679(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[2876] >> 0) & 1) << 31;
    v |= (unsigned int)((b[2876] >> 1) & 1) << 30;
    v |= (unsigned int)((b[2876] >> 2) & 1) << 29;
    v |= (unsigned int)((b[2876] >> 3) & 1) << 28;
    v |= (unsigned int)((b[2876] >> 4) & 1) << 27;
    v |= (unsigned int)((b[2876] >> 5) & 1) << 26;
    v |= (unsigned int)((b[2876] >> 6) & 1) << 25;
    v |= (unsigned int)((b[2876] >> 7) & 1) << 24;
    v |= (unsigned int)((b[2877] >> 0) & 1) << 23;
    v |= (unsigned int)((b[2877] >> 1) & 1) << 22;
    v |= (unsigned int)((b[2877] >> 2) & 1) << 21;
    v |= (unsigned int)((b[2877] >> 3) & 1) << 20;
    v |= (unsigned int)((b[2877] >> 4) & 1) << 19;
    v |= (unsigned int)((b[2877] >> 5) & 1) << 18;
    v |= (unsigned int)((b[2877] >> 6) & 1) << 17;
    v |= (unsigned int)((b[2877] >> 7) & 1) << 16;
    v |= (unsigned int)((b[2878] >> 7) & 1) << 15;
    v |= (unsigned int)((b[2878] >> 6) & 1) << 14;
    v |= (unsigned int)((b[2878] >> 5) & 1) << 13;
    v |= (unsigned int)((b[2878] >> 4) & 1) << 12;
    v |= (unsigned int)((b[2878] >> 3) & 1) << 11;
    v |= (unsigned int)((b[2878] >> 2) & 1) << 10;
    v |= (unsigned int)((b[2878] >> 1) & 1) << 9;
    v |= (unsigned int)((b[2878] >> 0) & 1) << 8;
    v |= (unsigned int)((b[2879] >> 7) & 1) << 7;
    v |= (unsigned int)((b[2879] >> 6) & 1) << 6;
    v |= (unsigned int)((b[2879] >> 5) & 1) << 5;
    v |= (unsigned int)((b[2879] >> 4) & 1) << 4;
    v |= (unsigned int)((b[2879] >> 3) & 1) << 3;
    v |= (unsigned int)((b[2879] >> 2) & 1) << 2;
    v |= (unsigned int)((b[2879] >> 1) & 1) << 1;
    v |= (unsigned int)((b[2879] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk679(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[2876] = (unsigned char)((b[2876] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[2876] = (unsigned char)((b[2876] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[2876] = (unsigned char)((b[2876] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[2876] = (unsigned char)((b[2876] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[2876] = (unsigned char)((b[2876] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[2876] = (unsigned char)((b[2876] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[2876] = (unsigned char)((b[2876] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[2876] = (unsigned char)((b[2876] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[2877] = (unsigned char)((b[2877] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[2878] = (unsigned char)((b[2878] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[2879] = (unsigned char)((b[2879] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk759(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[3236] >> 0) & 1) << 31;
    v |= (unsigned int)((b[3236] >> 1) & 1) << 30;
    v |= (unsigned int)((b[3236] >> 2) & 1) << 29;
    v |= (unsigned int)((b[3236] >> 3) & 1) << 28;
    v |= (unsigned int)((b[3236] >> 4) & 1) << 27;
    v |= (unsigned int)((b[3236] >> 5) & 1) << 26;
    v |= (unsigned int)((b[3236] >> 6) & 1) << 25;
    v |= (unsigned int)((b[3236] >> 7) & 1) << 24;
    v |= (unsigned int)((b[3237] >> 0) & 1) << 23;
    v |= (unsigned int)((b[3237] >> 1) & 1) << 22;
    v |= (unsigned int)((b[3237] >> 2) & 1) << 21;
    v |= (unsigned int)((b[3237] >> 3) & 1) << 20;
    v |= (unsigned int)((b[3237] >> 4) & 1) << 19;
    v |= (unsigned int)((b[3237] >> 5) & 1) << 18;
    v |= (unsigned int)((b[3237] >> 6) & 1) << 17;
    v |= (unsigned int)((b[3237] >> 7) & 1) << 16;
    v |= (unsigned int)((b[3238] >> 7) & 1) << 15;
    v |= (unsigned int)((b[3238] >> 6) & 1) << 14;
    v |= (unsigned int)((b[3238] >> 5) & 1) << 13;
    v |= (unsigned int)((b[3238] >> 4) & 1) << 12;
    v |= (unsigned int)((b[3238] >> 3) & 1) << 11;
    v |= (unsigned int)((b[3238] >> 2) & 1) << 10;
    v |= (unsigned int)((b[3238] >> 1) & 1) << 9;
    v |= (unsigned int)((b[3238] >> 0) & 1) << 8;
    v |= (unsigned int)((b[3239] >> 7) & 1) << 7;
    v |= (unsigned int)((b[3239] >> 6) & 1) << 6;
    v |= (unsigned int)((b[3239] >> 5) & 1) << 5;
    v |= (unsigned int)((b[3239] >> 4) & 1) << 4;
    v |= (unsigned int)((b[3239] >> 3) & 1) << 3;
    v |= (unsigned int)((b[3239] >> 2) & 1) << 2;
    v |= (unsigned int)((b[3239] >> 1) & 1) << 1;
    v |= (unsigned int)((b[3239] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk759(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[3236] = (unsigned char)((b[3236] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[3236] = (unsigned char)((b[3236] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[3236] = (unsigned char)((b[3236] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[3236] = (unsigned char)((b[3236] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[3236] = (unsigned char)((b[3236] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[3236] = (unsigned char)((b[3236] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[3236] = (unsigned char)((b[3236] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[3236] = (unsigned char)((b[3236] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[3237] = (unsigned char)((b[3237] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[3238] = (unsigned char)((b[3238] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[3239] = (unsigned char)((b[3239] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk839(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[3596] >> 0) & 1) << 31;
    v |= (unsigned int)((b[3596] >> 1) & 1) << 30;
    v |= (unsigned int)((b[3596] >> 2) & 1) << 29;
    v |= (unsigned int)((b[3596] >> 3) & 1) << 28;
    v |= (unsigned int)((b[3596] >> 4) & 1) << 27;
    v |= (unsigned int)((b[3596] >> 5) & 1) << 26;
    v |= (unsigned int)((b[3596] >> 6) & 1) << 25;
    v |= (unsigned int)((b[3596] >> 7) & 1) << 24;
    v |= (unsigned int)((b[3597] >> 0) & 1) << 23;
    v |= (unsigned int)((b[3597] >> 1) & 1) << 22;
    v |= (unsigned int)((b[3597] >> 2) & 1) << 21;
    v |= (unsigned int)((b[3597] >> 3) & 1) << 20;
    v |= (unsigned int)((b[3597] >> 4) & 1) << 19;
    v |= (unsigned int)((b[3597] >> 5) & 1) << 18;
    v |= (unsigned int)((b[3597] >> 6) & 1) << 17;
    v |= (unsigned int)((b[3597] >> 7) & 1) << 16;
    v |= (unsigned int)((b[3598] >> 7) & 1) << 15;
    v |= (unsigned int)((b[3598] >> 6) & 1) << 14;
    v |= (unsigned int)((b[3598] >> 5) & 1) << 13;
    v |= (unsigned int)((b[3598] >> 4) & 1) << 12;
    v |= (unsigned int)((b[3598] >> 3) & 1) << 11;
    v |= (unsigned int)((b[3598] >> 2) & 1) << 10;
    v |= (unsigned int)((b[3598] >> 1) & 1) << 9;
    v |= (unsigned int)((b[3598] >> 0) & 1) << 8;
    v |= (unsigned int)((b[3599] >> 7) & 1) << 7;
    v |= (unsigned int)((b[3599] >> 6) & 1) << 6;
    v |= (unsigned int)((b[3599] >> 5) & 1) << 5;
    v |= (unsigned int)((b[3599] >> 4) & 1) << 4;
    v |= (unsigned int)((b[3599] >> 3) & 1) << 3;
    v |= (unsigned int)((b[3599] >> 2) & 1) << 2;
    v |= (unsigned int)((b[3599] >> 1) & 1) << 1;
    v |= (unsigned int)((b[3599] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk839(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[3596] = (unsigned char)((b[3596] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[3596] = (unsigned char)((b[3596] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[3596] = (unsigned char)((b[3596] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[3596] = (unsigned char)((b[3596] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[3596] = (unsigned char)((b[3596] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[3596] = (unsigned char)((b[3596] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[3596] = (unsigned char)((b[3596] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[3596] = (unsigned char)((b[3596] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[3597] = (unsigned char)((b[3597] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[3598] = (unsigned char)((b[3598] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[3599] = (unsigned char)((b[3599] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk919(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[3956] >> 0) & 1) << 31;
    v |= (unsigned int)((b[3956] >> 1) & 1) << 30;
    v |= (unsigned int)((b[3956] >> 2) & 1) << 29;
    v |= (unsigned int)((b[3956] >> 3) & 1) << 28;
    v |= (unsigned int)((b[3956] >> 4) & 1) << 27;
    v |= (unsigned int)((b[3956] >> 5) & 1) << 26;
    v |= (unsigned int)((b[3956] >> 6) & 1) << 25;
    v |= (unsigned int)((b[3956] >> 7) & 1) << 24;
    v |= (unsigned int)((b[3957] >> 0) & 1) << 23;
    v |= (unsigned int)((b[3957] >> 1) & 1) << 22;
    v |= (unsigned int)((b[3957] >> 2) & 1) << 21;
    v |= (unsigned int)((b[3957] >> 3) & 1) << 20;
    v |= (unsigned int)((b[3957] >> 4) & 1) << 19;
    v |= (unsigned int)((b[3957] >> 5) & 1) << 18;
    v |= (unsigned int)((b[3957] >> 6) & 1) << 17;
    v |= (unsigned int)((b[3957] >> 7) & 1) << 16;
    v |= (unsigned int)((b[3958] >> 7) & 1) << 15;
    v |= (unsigned int)((b[3958] >> 6) & 1) << 14;
    v |= (unsigned int)((b[3958] >> 5) & 1) << 13;
    v |= (unsigned int)((b[3958] >> 4) & 1) << 12;
    v |= (unsigned int)((b[3958] >> 3) & 1) << 11;
    v |= (unsigned int)((b[3958] >> 2) & 1) << 10;
    v |= (unsigned int)((b[3958] >> 1) & 1) << 9;
    v |= (unsigned int)((b[3958] >> 0) & 1) << 8;
    v |= (unsigned int)((b[3959] >> 7) & 1) << 7;
    v |= (unsigned int)((b[3959] >> 6) & 1) << 6;
    v |= (unsigned int)((b[3959] >> 5) & 1) << 5;
    v |= (unsigned int)((b[3959] >> 4) & 1) << 4;
    v |= (unsigned int)((b[3959] >> 3) & 1) << 3;
    v |= (unsigned int)((b[3959] >> 2) & 1) << 2;
    v |= (unsigned int)((b[3959] >> 1) & 1) << 1;
    v |= (unsigned int)((b[3959] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk919(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[3956] = (unsigned char)((b[3956] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[3956] = (unsigned char)((b[3956] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[3956] = (unsigned char)((b[3956] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[3956] = (unsigned char)((b[3956] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[3956] = (unsigned char)((b[3956] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[3956] = (unsigned char)((b[3956] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[3956] = (unsigned char)((b[3956] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[3956] = (unsigned char)((b[3956] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[3957] = (unsigned char)((b[3957] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[3958] = (unsigned char)((b[3958] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[3959] = (unsigned char)((b[3959] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk999(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[4316] >> 0) & 1) << 31;
    v |= (unsigned int)((b[4316] >> 1) & 1) << 30;
    v |= (unsigned int)((b[4316] >> 2) & 1) << 29;
    v |= (unsigned int)((b[4316] >> 3) & 1) << 28;
    v |= (unsigned int)((b[4316] >> 4) & 1) << 27;
    v |= (unsigned int)((b[4316] >> 5) & 1) << 26;
    v |= (unsigned int)((b[4316] >> 6) & 1) << 25;
    v |= (unsigned int)((b[4316] >> 7) & 1) << 24;
    v |= (unsigned int)((b[4317] >> 0) & 1) << 23;
    v |= (unsigned int)((b[4317] >> 1) & 1) << 22;
    v |= (unsigned int)((b[4317] >> 2) & 1) << 21;
    v |= (unsigned int)((b[4317] >> 3) & 1) << 20;
    v |= (unsigned int)((b[4317] >> 4) & 1) << 19;
    v |= (unsigned int)((b[4317] >> 5) & 1) << 18;
    v |= (unsigned int)((b[4317] >> 6) & 1) << 17;
    v |= (unsigned int)((b[4317] >> 7) & 1) << 16;
    v |= (unsigned int)((b[4318] >> 7) & 1) << 15;
    v |= (unsigned int)((b[4318] >> 6) & 1) << 14;
    v |= (unsigned int)((b[4318] >> 5) & 1) << 13;
    v |= (unsigned int)((b[4318] >> 4) & 1) << 12;
    v |= (unsigned int)((b[4318] >> 3) & 1) << 11;
    v |= (unsigned int)((b[4318] >> 2) & 1) << 10;
    v |= (unsigned int)((b[4318] >> 1) & 1) << 9;
    v |= (unsigned int)((b[4318] >> 0) & 1) << 8;
    v |= (unsigned int)((b[4319] >> 7) & 1) << 7;
    v |= (unsigned int)((b[4319] >> 6) & 1) << 6;
    v |= (unsigned int)((b[4319] >> 5) & 1) << 5;
    v |= (unsigned int)((b[4319] >> 4) & 1) << 4;
    v |= (unsigned int)((b[4319] >> 3) & 1) << 3;
    v |= (unsigned int)((b[4319] >> 2) & 1) << 2;
    v |= (unsigned int)((b[4319] >> 1) & 1) << 1;
    v |= (unsigned int)((b[4319] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk999(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[4316] = (unsigned char)((b[4316] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[4316] = (unsigned char)((b[4316] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[4316] = (unsigned char)((b[4316] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[4316] = (unsigned char)((b[4316] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[4316] = (unsigned char)((b[4316] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[4316] = (unsigned char)((b[4316] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[4316] = (unsigned char)((b[4316] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[4316] = (unsigned char)((b[4316] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[4317] = (unsigned char)((b[4317] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[4318] = (unsigned char)((b[4318] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[4319] = (unsigned char)((b[4319] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk1079(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[4676] >> 0) & 1) << 31;
    v |= (unsigned int)((b[4676] >> 1) & 1) << 30;
    v |= (unsigned int)((b[4676] >> 2) & 1) << 29;
    v |= (unsigned int)((b[4676] >> 3) & 1) << 28;
    v |= (unsigned int)((b[4676] >> 4) & 1) << 27;
    v |= (unsigned int)((b[4676] >> 5) & 1) << 26;
    v |= (unsigned int)((b[4676] >> 6) & 1) << 25;
    v |= (unsigned int)((b[4676] >> 7) & 1) << 24;
    v |= (unsigned int)((b[4677] >> 0) & 1) << 23;
    v |= (unsigned int)((b[4677] >> 1) & 1) << 22;
    v |= (unsigned int)((b[4677] >> 2) & 1) << 21;
    v |= (unsigned int)((b[4677] >> 3) & 1) << 20;
    v |= (unsigned int)((b[4677] >> 4) & 1) << 19;
    v |= (unsigned int)((b[4677] >> 5) & 1) << 18;
    v |= (unsigned int)((b[4677] >> 6) & 1) << 17;
    v |= (unsigned int)((b[4677] >> 7) & 1) << 16;
    v |= (unsigned int)((b[4678] >> 7) & 1) << 15;
    v |= (unsigned int)((b[4678] >> 6) & 1) << 14;
    v |= (unsigned int)((b[4678] >> 5) & 1) << 13;
    v |= (unsigned int)((b[4678] >> 4) & 1) << 12;
    v |= (unsigned int)((b[4678] >> 3) & 1) << 11;
    v |= (unsigned int)((b[4678] >> 2) & 1) << 10;
    v |= (unsigned int)((b[4678] >> 1) & 1) << 9;
    v |= (unsigned int)((b[4678] >> 0) & 1) << 8;
    v |= (unsigned int)((b[4679] >> 7) & 1) << 7;
    v |= (unsigned int)((b[4679] >> 6) & 1) << 6;
    v |= (unsigned int)((b[4679] >> 5) & 1) << 5;
    v |= (unsigned int)((b[4679] >> 4) & 1) << 4;
    v |= (unsigned int)((b[4679] >> 3) & 1) << 3;
    v |= (unsigned int)((b[4679] >> 2) & 1) << 2;
    v |= (unsigned int)((b[4679] >> 1) & 1) << 1;
    v |= (unsigned int)((b[4679] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk1079(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[4676] = (unsigned char)((b[4676] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[4676] = (unsigned char)((b[4676] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[4676] = (unsigned char)((b[4676] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[4676] = (unsigned char)((b[4676] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[4676] = (unsigned char)((b[4676] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[4676] = (unsigned char)((b[4676] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[4676] = (unsigned char)((b[4676] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[4676] = (unsigned char)((b[4676] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[4677] = (unsigned char)((b[4677] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[4678] = (unsigned char)((b[4678] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[4679] = (unsigned char)((b[4679] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk1159(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[5036] >> 0) & 1) << 31;
    v |= (unsigned int)((b[5036] >> 1) & 1) << 30;
    v |= (unsigned int)((b[5036] >> 2) & 1) << 29;
    v |= (unsigned int)((b[5036] >> 3) & 1) << 28;
    v |= (unsigned int)((b[5036] >> 4) & 1) << 27;
    v |= (unsigned int)((b[5036] >> 5) & 1) << 26;
    v |= (unsigned int)((b[5036] >> 6) & 1) << 25;
    v |= (unsigned int)((b[5036] >> 7) & 1) << 24;
    v |= (unsigned int)((b[5037] >> 0) & 1) << 23;
    v |= (unsigned int)((b[5037] >> 1) & 1) << 22;
    v |= (unsigned int)((b[5037] >> 2) & 1) << 21;
    v |= (unsigned int)((b[5037] >> 3) & 1) << 20;
    v |= (unsigned int)((b[5037] >> 4) & 1) << 19;
    v |= (unsigned int)((b[5037] >> 5) & 1) << 18;
    v |= (unsigned int)((b[5037] >> 6) & 1) << 17;
    v |= (unsigned int)((b[5037] >> 7) & 1) << 16;
    v |= (unsigned int)((b[5038] >> 7) & 1) << 15;
    v |= (unsigned int)((b[5038] >> 6) & 1) << 14;
    v |= (unsigned int)((b[5038] >> 5) & 1) << 13;
    v |= (unsigned int)((b[5038] >> 4) & 1) << 12;
    v |= (unsigned int)((b[5038] >> 3) & 1) << 11;
    v |= (unsigned int)((b[5038] >> 2) & 1) << 10;
    v |= (unsigned int)((b[5038] >> 1) & 1) << 9;
    v |= (unsigned int)((b[5038] >> 0) & 1) << 8;
    v |= (unsigned int)((b[5039] >> 7) & 1) << 7;
    v |= (unsigned int)((b[5039] >> 6) & 1) << 6;
    v |= (unsigned int)((b[5039] >> 5) & 1) << 5;
    v |= (unsigned int)((b[5039] >> 4) & 1) << 4;
    v |= (unsigned int)((b[5039] >> 3) & 1) << 3;
    v |= (unsigned int)((b[5039] >> 2) & 1) << 2;
    v |= (unsigned int)((b[5039] >> 1) & 1) << 1;
    v |= (unsigned int)((b[5039] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk1159(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[5036] = (unsigned char)((b[5036] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[5036] = (unsigned char)((b[5036] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[5036] = (unsigned char)((b[5036] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[5036] = (unsigned char)((b[5036] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[5036] = (unsigned char)((b[5036] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[5036] = (unsigned char)((b[5036] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[5036] = (unsigned char)((b[5036] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[5036] = (unsigned char)((b[5036] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[5037] = (unsigned char)((b[5037] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[5038] = (unsigned char)((b[5038] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[5039] = (unsigned char)((b[5039] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk1239(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[5396] >> 0) & 1) << 31;
    v |= (unsigned int)((b[5396] >> 1) & 1) << 30;
    v |= (unsigned int)((b[5396] >> 2) & 1) << 29;
    v |= (unsigned int)((b[5396] >> 3) & 1) << 28;
    v |= (unsigned int)((b[5396] >> 4) & 1) << 27;
    v |= (unsigned int)((b[5396] >> 5) & 1) << 26;
    v |= (unsigned int)((b[5396] >> 6) & 1) << 25;
    v |= (unsigned int)((b[5396] >> 7) & 1) << 24;
    v |= (unsigned int)((b[5397] >> 0) & 1) << 23;
    v |= (unsigned int)((b[5397] >> 1) & 1) << 22;
    v |= (unsigned int)((b[5397] >> 2) & 1) << 21;
    v |= (unsigned int)((b[5397] >> 3) & 1) << 20;
    v |= (unsigned int)((b[5397] >> 4) & 1) << 19;
    v |= (unsigned int)((b[5397] >> 5) & 1) << 18;
    v |= (unsigned int)((b[5397] >> 6) & 1) << 17;
    v |= (unsigned int)((b[5397] >> 7) & 1) << 16;
    v |= (unsigned int)((b[5398] >> 7) & 1) << 15;
    v |= (unsigned int)((b[5398] >> 6) & 1) << 14;
    v |= (unsigned int)((b[5398] >> 5) & 1) << 13;
    v |= (unsigned int)((b[5398] >> 4) & 1) << 12;
    v |= (unsigned int)((b[5398] >> 3) & 1) << 11;
    v |= (unsigned int)((b[5398] >> 2) & 1) << 10;
    v |= (unsigned int)((b[5398] >> 1) & 1) << 9;
    v |= (unsigned int)((b[5398] >> 0) & 1) << 8;
    v |= (unsigned int)((b[5399] >> 7) & 1) << 7;
    v |= (unsigned int)((b[5399] >> 6) & 1) << 6;
    v |= (unsigned int)((b[5399] >> 5) & 1) << 5;
    v |= (unsigned int)((b[5399] >> 4) & 1) << 4;
    v |= (unsigned int)((b[5399] >> 3) & 1) << 3;
    v |= (unsigned int)((b[5399] >> 2) & 1) << 2;
    v |= (unsigned int)((b[5399] >> 1) & 1) << 1;
    v |= (unsigned int)((b[5399] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk1239(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[5396] = (unsigned char)((b[5396] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[5396] = (unsigned char)((b[5396] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[5396] = (unsigned char)((b[5396] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[5396] = (unsigned char)((b[5396] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[5396] = (unsigned char)((b[5396] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[5396] = (unsigned char)((b[5396] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[5396] = (unsigned char)((b[5396] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[5396] = (unsigned char)((b[5396] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[5397] = (unsigned char)((b[5397] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[5398] = (unsigned char)((b[5398] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[5399] = (unsigned char)((b[5399] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk1319(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[5756] >> 0) & 1) << 31;
    v |= (unsigned int)((b[5756] >> 1) & 1) << 30;
    v |= (unsigned int)((b[5756] >> 2) & 1) << 29;
    v |= (unsigned int)((b[5756] >> 3) & 1) << 28;
    v |= (unsigned int)((b[5756] >> 4) & 1) << 27;
    v |= (unsigned int)((b[5756] >> 5) & 1) << 26;
    v |= (unsigned int)((b[5756] >> 6) & 1) << 25;
    v |= (unsigned int)((b[5756] >> 7) & 1) << 24;
    v |= (unsigned int)((b[5757] >> 0) & 1) << 23;
    v |= (unsigned int)((b[5757] >> 1) & 1) << 22;
    v |= (unsigned int)((b[5757] >> 2) & 1) << 21;
    v |= (unsigned int)((b[5757] >> 3) & 1) << 20;
    v |= (unsigned int)((b[5757] >> 4) & 1) << 19;
    v |= (unsigned int)((b[5757] >> 5) & 1) << 18;
    v |= (unsigned int)((b[5757] >> 6) & 1) << 17;
    v |= (unsigned int)((b[5757] >> 7) & 1) << 16;
    v |= (unsigned int)((b[5758] >> 7) & 1) << 15;
    v |= (unsigned int)((b[5758] >> 6) & 1) << 14;
    v |= (unsigned int)((b[5758] >> 5) & 1) << 13;
    v |= (unsigned int)((b[5758] >> 4) & 1) << 12;
    v |= (unsigned int)((b[5758] >> 3) & 1) << 11;
    v |= (unsigned int)((b[5758] >> 2) & 1) << 10;
    v |= (unsigned int)((b[5758] >> 1) & 1) << 9;
    v |= (unsigned int)((b[5758] >> 0) & 1) << 8;
    v |= (unsigned int)((b[5759] >> 7) & 1) << 7;
    v |= (unsigned int)((b[5759] >> 6) & 1) << 6;
    v |= (unsigned int)((b[5759] >> 5) & 1) << 5;
    v |= (unsigned int)((b[5759] >> 4) & 1) << 4;
    v |= (unsigned int)((b[5759] >> 3) & 1) << 3;
    v |= (unsigned int)((b[5759] >> 2) & 1) << 2;
    v |= (unsigned int)((b[5759] >> 1) & 1) << 1;
    v |= (unsigned int)((b[5759] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk1319(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[5756] = (unsigned char)((b[5756] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[5756] = (unsigned char)((b[5756] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[5756] = (unsigned char)((b[5756] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[5756] = (unsigned char)((b[5756] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[5756] = (unsigned char)((b[5756] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[5756] = (unsigned char)((b[5756] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[5756] = (unsigned char)((b[5756] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[5756] = (unsigned char)((b[5756] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[5757] = (unsigned char)((b[5757] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[5758] = (unsigned char)((b[5758] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[5759] = (unsigned char)((b[5759] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk1399(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[6116] >> 0) & 1) << 31;
    v |= (unsigned int)((b[6116] >> 1) & 1) << 30;
    v |= (unsigned int)((b[6116] >> 2) & 1) << 29;
    v |= (unsigned int)((b[6116] >> 3) & 1) << 28;
    v |= (unsigned int)((b[6116] >> 4) & 1) << 27;
    v |= (unsigned int)((b[6116] >> 5) & 1) << 26;
    v |= (unsigned int)((b[6116] >> 6) & 1) << 25;
    v |= (unsigned int)((b[6116] >> 7) & 1) << 24;
    v |= (unsigned int)((b[6117] >> 0) & 1) << 23;
    v |= (unsigned int)((b[6117] >> 1) & 1) << 22;
    v |= (unsigned int)((b[6117] >> 2) & 1) << 21;
    v |= (unsigned int)((b[6117] >> 3) & 1) << 20;
    v |= (unsigned int)((b[6117] >> 4) & 1) << 19;
    v |= (unsigned int)((b[6117] >> 5) & 1) << 18;
    v |= (unsigned int)((b[6117] >> 6) & 1) << 17;
    v |= (unsigned int)((b[6117] >> 7) & 1) << 16;
    v |= (unsigned int)((b[6118] >> 7) & 1) << 15;
    v |= (unsigned int)((b[6118] >> 6) & 1) << 14;
    v |= (unsigned int)((b[6118] >> 5) & 1) << 13;
    v |= (unsigned int)((b[6118] >> 4) & 1) << 12;
    v |= (unsigned int)((b[6118] >> 3) & 1) << 11;
    v |= (unsigned int)((b[6118] >> 2) & 1) << 10;
    v |= (unsigned int)((b[6118] >> 1) & 1) << 9;
    v |= (unsigned int)((b[6118] >> 0) & 1) << 8;
    v |= (unsigned int)((b[6119] >> 7) & 1) << 7;
    v |= (unsigned int)((b[6119] >> 6) & 1) << 6;
    v |= (unsigned int)((b[6119] >> 5) & 1) << 5;
    v |= (unsigned int)((b[6119] >> 4) & 1) << 4;
    v |= (unsigned int)((b[6119] >> 3) & 1) << 3;
    v |= (unsigned int)((b[6119] >> 2) & 1) << 2;
    v |= (unsigned int)((b[6119] >> 1) & 1) << 1;
    v |= (unsigned int)((b[6119] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk1399(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[6116] = (unsigned char)((b[6116] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[6116] = (unsigned char)((b[6116] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[6116] = (unsigned char)((b[6116] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[6116] = (unsigned char)((b[6116] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[6116] = (unsigned char)((b[6116] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[6116] = (unsigned char)((b[6116] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[6116] = (unsigned char)((b[6116] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[6116] = (unsigned char)((b[6116] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[6117] = (unsigned char)((b[6117] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[6118] = (unsigned char)((b[6118] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[6119] = (unsigned char)((b[6119] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
static inline unsigned int mexbits_get_Memcard__unk1479(const void *o)
{
    const unsigned char *b = (const unsigned char *)o;
    unsigned int v = 0;
    v |= (unsigned int)((b[6476] >> 0) & 1) << 31;
    v |= (unsigned int)((b[6476] >> 1) & 1) << 30;
    v |= (unsigned int)((b[6476] >> 2) & 1) << 29;
    v |= (unsigned int)((b[6476] >> 3) & 1) << 28;
    v |= (unsigned int)((b[6476] >> 4) & 1) << 27;
    v |= (unsigned int)((b[6476] >> 5) & 1) << 26;
    v |= (unsigned int)((b[6476] >> 6) & 1) << 25;
    v |= (unsigned int)((b[6476] >> 7) & 1) << 24;
    v |= (unsigned int)((b[6477] >> 0) & 1) << 23;
    v |= (unsigned int)((b[6477] >> 1) & 1) << 22;
    v |= (unsigned int)((b[6477] >> 2) & 1) << 21;
    v |= (unsigned int)((b[6477] >> 3) & 1) << 20;
    v |= (unsigned int)((b[6477] >> 4) & 1) << 19;
    v |= (unsigned int)((b[6477] >> 5) & 1) << 18;
    v |= (unsigned int)((b[6477] >> 6) & 1) << 17;
    v |= (unsigned int)((b[6477] >> 7) & 1) << 16;
    v |= (unsigned int)((b[6478] >> 7) & 1) << 15;
    v |= (unsigned int)((b[6478] >> 6) & 1) << 14;
    v |= (unsigned int)((b[6478] >> 5) & 1) << 13;
    v |= (unsigned int)((b[6478] >> 4) & 1) << 12;
    v |= (unsigned int)((b[6478] >> 3) & 1) << 11;
    v |= (unsigned int)((b[6478] >> 2) & 1) << 10;
    v |= (unsigned int)((b[6478] >> 1) & 1) << 9;
    v |= (unsigned int)((b[6478] >> 0) & 1) << 8;
    v |= (unsigned int)((b[6479] >> 7) & 1) << 7;
    v |= (unsigned int)((b[6479] >> 6) & 1) << 6;
    v |= (unsigned int)((b[6479] >> 5) & 1) << 5;
    v |= (unsigned int)((b[6479] >> 4) & 1) << 4;
    v |= (unsigned int)((b[6479] >> 3) & 1) << 3;
    v |= (unsigned int)((b[6479] >> 2) & 1) << 2;
    v |= (unsigned int)((b[6479] >> 1) & 1) << 1;
    v |= (unsigned int)((b[6479] >> 0) & 1) << 0;
    return v;
}
static inline void mexbits_set_Memcard__unk1479(void *o, unsigned int v)
{
    unsigned char *b = (unsigned char *)o;
    b[6476] = (unsigned char)((b[6476] & ~(1u << 0)) | (((v >> 31) & 1u) << 0));
    b[6476] = (unsigned char)((b[6476] & ~(1u << 1)) | (((v >> 30) & 1u) << 1));
    b[6476] = (unsigned char)((b[6476] & ~(1u << 2)) | (((v >> 29) & 1u) << 2));
    b[6476] = (unsigned char)((b[6476] & ~(1u << 3)) | (((v >> 28) & 1u) << 3));
    b[6476] = (unsigned char)((b[6476] & ~(1u << 4)) | (((v >> 27) & 1u) << 4));
    b[6476] = (unsigned char)((b[6476] & ~(1u << 5)) | (((v >> 26) & 1u) << 5));
    b[6476] = (unsigned char)((b[6476] & ~(1u << 6)) | (((v >> 25) & 1u) << 6));
    b[6476] = (unsigned char)((b[6476] & ~(1u << 7)) | (((v >> 24) & 1u) << 7));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 0)) | (((v >> 23) & 1u) << 0));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 1)) | (((v >> 22) & 1u) << 1));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 2)) | (((v >> 21) & 1u) << 2));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 3)) | (((v >> 20) & 1u) << 3));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 4)) | (((v >> 19) & 1u) << 4));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 5)) | (((v >> 18) & 1u) << 5));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 6)) | (((v >> 17) & 1u) << 6));
    b[6477] = (unsigned char)((b[6477] & ~(1u << 7)) | (((v >> 16) & 1u) << 7));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 7)) | (((v >> 15) & 1u) << 7));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 6)) | (((v >> 14) & 1u) << 6));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 5)) | (((v >> 13) & 1u) << 5));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 4)) | (((v >> 12) & 1u) << 4));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 3)) | (((v >> 11) & 1u) << 3));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 2)) | (((v >> 10) & 1u) << 2));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 1)) | (((v >> 9) & 1u) << 1));
    b[6478] = (unsigned char)((b[6478] & ~(1u << 0)) | (((v >> 8) & 1u) << 0));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 7)) | (((v >> 7) & 1u) << 7));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 6)) | (((v >> 6) & 1u) << 6));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 5)) | (((v >> 5) & 1u) << 5));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 4)) | (((v >> 4) & 1u) << 4));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 3)) | (((v >> 3) & 1u) << 3));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 2)) | (((v >> 2) & 1u) << 2));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 1)) | (((v >> 1) & 1u) << 1));
    b[6479] = (unsigned char)((b[6479] & ~(1u << 0)) | (((v >> 0) & 1u) << 0));
}
