/* Generated by tools/tmce/gen_mextk.py: what the native MexTK headers add. */
#pragma once
#include <stdint.h>

/* A pointer slot in disc data (a .dat file): 4 bytes holding the real address, which sits below
 * 4 GB natively (MEM1 and the game image). */
#define MEX_DP(slot) ((void *)(uintptr_t)(unsigned int)(slot))

/* C library functions MexTK declares with the console int sizes: natively they go to wrappers
 * (native/tmce_runtime.c), so a 32-bit size never lands in a 64-bit size_t parameter. */
#define memcpy mex_memcpy
#define memmove mex_memmove
#define memset mex_memset
#define strncmp mex_strncmp
#define strcpy mex_strcpy
#define strlen mex_strlen
#define calloc mex_calloc
#define _vsprintf mex__vsprintf
