// English launcher text, the fallback for every language. Keys match lang/<code>.txt.
// SPDX-License-Identifier: GPL-2.0-or-later
{"mode.vanilla", "Vanilla"},
{"mode.custom", "Custom ISO"},
{"lobby.build_unknown", "unknown build"},
{"lobby.other_player", "The other player"},
{"lobby.sent", "Match request sent to {name}."},
{"lobby.delivered", "Delivered. Waiting for {name} to answer."},
{"lobby.accepted_start", "{name} accepted. Starting the match..."},
{"lobby.cancelled", "{name} cancelled the match request."},
{"lobby.cancelled_busy", "{name} started something else, so the request was cancelled."},
{"lobby.withdrawn", "{name} withdrew the match request."},
{"lobby.expired", "The match request to {name} expired without an answer."},
{"lobby.missed", "You missed a match request from {name}."},
{"lobby.request_from", "Match request from {name}"},
// Five lines here (these two, lobby.error.profile, lobby.error.code_format and lobby.code_copied) are
// never said by the launcher built without the Slippi layer, which has its own lobby.p2p.* lines for
// the same moments, so that build's table leaves them out.
#ifndef MELEE_NO_SLIPPI
{"lobby.unreachable", "Can't reach {name}. Use Slippi Direct with their code: {code}"},
{"lobby.accept_unreachable", "Can't reach {name} to start the match. Use Slippi Direct with their code: {code}"},
#endif
{"lobby.no_answer_legacy", "No answer from {name}. They are on {version}: both players need 0.8.5 or newer."},
{"lobby.clock_skew", "{name}'s PC clock is {minutes} minutes off, so you can't see each other. Set the time automatically in Windows settings."},
{"lobby.identity_copied", "Your lobby ID was copied."},
{"lobby.refused.hidden", "{name} tried to start a match, but you are not in the public lobby."},
{"lobby.refused.busy", "{name} tried to start a match while you were busy."},
{"lobby.refused.not_ready", "{name} tried to start a match, but your game setup is not finished. Finish it on the Play page."},
{"lobby.refused.sender_not_ready", "{name} tried to start a match, but their game setup is not finished."},
{"lobby.refused.build", "{name} tried to start a match on {theirs}, but you are on {mine}."},
{"lobby.refused.update_them", "{name} tried to start a match, but they are on {theirs} and you are on {mine}. They need to update."},
{"lobby.refused.update_you", "{name} tried to start a match, but they are on {theirs} and you are on {mine}. Update to play them."},
{"lobby.refused.answering", "{name} tried to start a match while you were answering another request."},
{"lobby.refused.mode_missing", "{name} wants to play {mode}, which you don't have installed."},
{"lobby.refused.mode_closed", "{name} wants to play {mode}, which you are not open to right now."},
{"lobby.refused.mode_version", "{name} wants to play {mode} {theirs}, but you have {mine}."},
{"lobby.refused.mode_hash", "{name} wants to play a custom ISO that is different from yours."},
{"lobby.refused.expired", "A match request from {name} expired."},
{"lobby.refused.other", "A match request from {name} could not go through."},
{"lobby.declined.hidden", "{name} is not in the public lobby."},
{"lobby.declined.busy", "{name} is in a game or another match."},
{"lobby.declined.not_ready", "{name} has not finished game setup."},
{"lobby.declined.sender_not_ready", "{name} sees your game setup as unfinished. Finish it on the Play page."},
{"lobby.declined.build", "{name} is on {theirs} and you are on {mine}. Choose the same Game Build."},
{"lobby.declined.update_them", "{name} is on {theirs} and you are on {mine}. They need to update."},
{"lobby.declined.update_you", "{name} is on {theirs} and you are on {mine}. Update to play them."},
{"lobby.declined.answering", "{name} is answering another match request."},
{"lobby.declined.mode_missing", "{name} does not have {mode} installed."},
{"lobby.declined.mode_closed", "{name} is not open to {mode} right now."},
{"lobby.declined.mode_version", "{name} has {mode} {theirs} and you have {mine}."},
{"lobby.declined.mode_hash", "{name} has a different custom ISO."},
{"lobby.declined.expired", "The request to {name} expired."},
{"lobby.declined.auto", "{name} could not take the match right now."},
{"lobby.declined.user", "{name} declined the match."},
{"lobby.declined.other", "{name} could not take the match: {reason}."},
{"lobby.friend.sent", "Friend request sent to {name}."},
{"lobby.friend.incoming", "{name} wants to add you as a friend."},
{"lobby.friend.accepted", "{name} is now your friend."},
{"lobby.friend.declined", "{name} declined your friend request."},
{"lobby.friend.already", "{name} is already your friend."},
{"lobby.friend.self", "That is your own code."},
{"lobby.friend.looking", "Looking for {code}. They need to be online in the launcher."},
{"lobby.friend.not_found", "Could not find {code}. They need to be online with launcher {version} or newer."},
{"lobby.friend.legacy", "{name} is on an older launcher and can only be added from the public lobby."},
{"lobby.error.bootstrap", "The peer address must be a reachable host:port."},
{"lobby.error.no_dht", "Cannot reach the lobby network. Check your internet connection."},
{"lobby.error.port", "Cannot open the lobby's network port."},
{"lobby.error.discovery", "Cannot start player discovery."},
{"lobby.error.save_identity", "Cannot save your lobby identity."},
{"lobby.error.identity", "Your lobby identity file is damaged. Delete lobby-peer-identity.json to make a new one."},
#ifndef MELEE_NO_SLIPPI
{"lobby.error.profile", "Your profile needs a name, a Slippi code and at least one main."},
#endif
{"lobby.error.iso_name", "The custom ISO name must be 1 to 32 plain characters."},
#ifndef MELEE_NO_SLIPPI
{"lobby.error.code_format", "A Slippi code looks like ABCD#123."},
#endif
{"lobby.error.too_many_lookups", "Too many friend searches at once. Try again in a minute."},
{"lobby.error.chat", "Messages must be 1 to 300 characters, one per second."},
{"lobby.error.offline", "That player is offline."},
{"lobby.error.friend_gone", "That friend request is no longer there."},
{"lobby.error.not_friend", "That player is not your friend."},
{"lobby.error.left", "{name} left the lobby."},
{"lobby.error.self_busy", "You are in a game or another match."},
{"lobby.error.self_not_ready", "Not ready yet: choose your Melee ISO on the Play page first."},
{"lobby.error.self_mode", "You can't play {mode} right now: install it or mark yourself open to it."},
{"lobby.error.pending", "A match request is already pending."},
{"lobby.error.expired", "That request expired or was cancelled."},
{"lobby.error.cannot_accept", "Only the invited player can accept, while free."},
{"lobby.error.unknown_action", "Unknown lobby action."},
{"lobby.players_online", "Players online ({count})"},
{"lobby.filter.button", "Show: {mode}"},
{"lobby.filter.all", "All"},
{"lobby.card.finish_setup", "Choose your Melee ISO on the Play page"},
{"lobby.card.setup_unfinished", "Setup not finished"},
{"lobby.invite", "Invite to Match"},
{"lobby.copy_code", "Copy code"},
#ifndef MELEE_NO_SLIPPI
{"lobby.code_copied", "Copied {code}. Use it in Slippi Direct."},
#endif
{"lobby.mod_disc_missing", "This match needs a mod disc this PC no longer has. Check the Mods page."},
{"lobby.starting_mod", "Match accepted. Starting {mode} on Static Recomp..."},
{"lobby.pm.button", "Private Chat"},
{"lobby.pm.sent", "Private chat request sent to {name}."},
{"lobby.pm.incoming", "{name} wants to chat privately."},
{"lobby.pm.request_from", "Private chat request from {name}"},
{"lobby.pm.request_detail", "Only the two of you see a private chat. Block stops their requests until you restart the launcher."},
{"lobby.pm.opened", "Private chat with {name} is open."},
{"lobby.pm.declined", "{name} declined the private chat."},
{"lobby.pm.declined.hidden", "{name} is not in the public lobby."},
{"lobby.pm.declined.full", "{name} has too many private chats open."},
{"lobby.pm.expired", "{name} did not answer the private chat request."},
{"lobby.pm.no_answer", "No answer from {name}. They may be unreachable, or on a version without private chat."},
{"lobby.pm.missed", "You missed a private chat request from {name}."},
{"lobby.pm.unsupported", "{name}'s version does not support private chat."},
{"lobby.pm.already", "You already have a private chat with {name}."},
{"lobby.pm.pending", "{name} has not answered your private chat request yet."},
{"lobby.pm.wait", "Wait a few seconds before sending another private chat request."},
{"lobby.pm.full", "Too many private chats are open. Close one first."},
{"lobby.pm.gone", "That private chat request is no longer there."},
{"lobby.pm.closed", "This private chat is closed."},
{"lobby.pm.closed_by", "{name} closed this chat."},
{"lobby.pm.blocked", "Blocked {name} until you restart the launcher."},
{"lobby.pm.empty", "Private chat with {name}. Only the two of you see these messages."},
{"lobby.pm.close", "Close chat"},
{"lobby.pm.block", "Close and block {name}"},
{"lobby.pm.tab_public", "Lobby"},
{"lobby.refused.p2p_version", "{name} tried to start a match, but their launcher cannot start a peer-to-peer match with yours. Both players need the same kind and version of launcher."},
{"lobby.declined.p2p_version", "{name}'s launcher cannot start a peer-to-peer match with yours. Both players need the same kind and version of launcher."},
{"lobby.p2p.unreachable", "Can't reach {name}. Ask them for their invite and use Connect."},
{"lobby.p2p.accept_unreachable", "Can't reach {name} to start the match. Ask them for their invite and use Connect."},
{"lobby.p2p.starting", "Match accepted. Starting the peer-to-peer match against {name}..."},
{"lobby.p2p.setup_failed", "The match could not start: its setup was not complete. Send another request."},
{"lobby.p2p.name", "Player: {name} ({code})"},
{"lobby.p2p.name_missing", "Choose your player name on the Lobby page, under Profile."},
{"lobby.p2p.identity_failed", "Your lobby identity file could not be read or made."},
{"lobby.p2p.setup_hint", "To play, choose your Melee disc on the Play page."},
{"lobby.p2p.fighter_button", "{character} | Color {number}"},
{"lobby.p2p.fighter_first", "First main ({character})"},
{"lobby.p2p.color", "Color {number}"},
{"lobby.p2p.color_menu", "Color"},
{"lobby.refused.p2p_fighter", "{name}'s launcher sent a character or color that does not exist. The match was not started."},
{"lobby.declined.p2p_fighter", "{name}'s launcher did not accept your character or color. Choose them again on the Lobby page, under Profile."},
{"lobby.search.button", "Find match"},
{"lobby.search.stop", "Stop searching"},
{"lobby.search.on", "Searching for a match. Stay on this page or keep the launcher open."},
{"lobby.search.off", "Stopped searching."},
{"lobby.search.asking", "Found {name}. Starting the match..."},
{"lobby.search.offline", "Go Online first: only players in the public lobby are paired."},
{"lobby.invite.cue", "Paste a player's invite to connect directly"},
{"lobby.invite.connect", "Connect"},
{"lobby.invite.copy", "Copy my invite"},
{"lobby.invite.copied", "Invite copied. Send it to the other player. Across the internet your router has to forward the lobby's UDP port {port}."},
{"lobby.invite.none", "Your invite is not ready yet. Go Online first."},
{"lobby.invite.bad", "That is not an invite. Ask the other player to press Copy my invite and send you the whole line."},
{"lobby.invite.self", "That is your own invite."},
{"lobby.invite.trying", "Connecting to {name}..."},
{"lobby.invite.found", "Connected to {name}. They are selected in the player list."},
{"lobby.invite.not_found", "No answer at the invite's addresses. The other player has to be online, and reachable: the same network, or a forwarded port."},
{"lobby.block.button", "Block"},
{"lobby.block.undo", "Unblock"},
{"lobby.blocked", "Blocked {name}. You will not be matched with them and their requests are ignored."},
{"lobby.unblocked", "Unblocked {name}."},
{"lobby.error.blocked", "You blocked {name}. Unblock them first."},
{"lobby.error.block_full", "The block list is full."},
{"lobby.profile.code", "Your player code (from your name and your key)"},
{"lobby.friend.code_cue", "Player code, e.g. FOX#123"},
{"lobby.friend.code_hint", "Enter an online player's code."},
{"lobby.p2p.error.profile", "Your profile needs a name and at least one main."},
{"lobby.p2p.error.code_format", "A player code looks like ABCD#123."},
{"lobby.p2p.code_copied", "Copied {code}."},
// P2P Direct in the launcher that also starts Slippi Direct: a test control on the Lobby page. The
// launcher built without the Slippi layer never says these, so its table leaves them out.
#ifndef MELEE_NO_SLIPPI
{"lobby.p2p.test_button", "P2P Direct (test)"},
{"lobby.p2p.test_tip", "Test: asks the selected player for a peer-to-peer match, without Slippi's servers. Both players need this version, Source Port selected, and a direct connection (the same network, or a forwarded port). One game, vanilla."},
{"lobby.p2p.test_request_from", "P2P Direct (test) request from {name}"},
{"lobby.p2p.test_detail", "peer to peer, no Slippi servers"},
{"lobby.p2p.test_online", "You're online for P2P Direct (test) only. Sign in through Slippi Launcher to use Slippi Direct too."},
{"lobby.p2p.no_route", "Can't reach {name} for P2P Direct. It needs a direct connection: the same network, or a forwarded port."},
{"lobby.p2p.error.engine", "P2P Direct needs Source Port. Select it under GAME BUILD on the Play page."},
{"lobby.p2p.error.vanilla", "P2P Direct plays vanilla only."},
{"lobby.p2p.error.launch_engine", "The P2P Direct match could not start: Source Port has to be the selected Game Build, with its game files and your disc in place. Select it on the Play page, then request another match."},
{"lobby.refused.p2p_engine", "{name} tried to start a P2P Direct match, but it needs Source Port selected on both sides."},
{"lobby.declined.p2p_engine", "P2P Direct needs Source Port selected on both sides. {name} or you are on another Game Build."},
{"lobby.error.self_no_account", "Slippi Direct needs a Slippi sign-in. Sign in through Slippi Launcher, or use P2P Direct (test)."},
{"lobby.refused.no_account", "{name} sent a Slippi Direct request, but you are not signed in to Slippi."},
{"lobby.declined.no_account", "{name} is not signed in to Slippi, so only P2P Direct (test) works with them."},
#endif
{"crash.offer", "The game crashed. Send a crash report so it can be fixed?\n\nThese files are sent:\n{files}\nThey contain the error, the game's log and your lobby log. Nothing else."},
